version: '3.8'

services:
  
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo:/docker-entrypoint-initdb.d:mongo-init.js
      - ./mongo_data:/data/db
      - ./:/usr/src/app
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./redis_data:/data    
  
  server:
    container_name: todo-backend-dev
    build:
      context: ./todo-backend
      dockerfile: dev.Dockerfile 
    ports:
      - 3000:3000
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis
    
  app:
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile
    ports:
      - 8081:3000
    container_name: todo-frontend
    depends_on:
      - server

  nginx:
    image: nginx:1.20.1
    volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-frontend-dev
    depends_on:
      - app
    
